### ISSUE TITLE
Python packages requirements

### ISSUE THREAD

**Issue by X-zy-0816** [lauraset/Super-resolution-building-height-estimation#1]
@lauraset,

Excellent, thank you for providing such amazing work. However, I encountered a few problems when trying to run the code. It seems that some Python libraries are missing, or I didn't find the correct packages. The missing libraries are as follows:

- `mygeoinfo`
- `imbalance`
- `aggregate_utils`

Could you please provide a requirements file or a list of the necessary packages?

Thanks for your time.

**Comment by lauraset** [comment]
Hi, @X-zy-0816. Thank you very much. I have updated the file `BH_loader.py` and relevant libraries were put in the `requirements.txt`. If there is any issue, please let me know!

**Comment by liuqiqi546** [comment]
Thank you very much for your sharing. I encountered an error while running predict_realesanet_feature_globle.py, which indicated: "No such file or directory: '.\weights\realesrgan\checkpoint.tar'". Could you provide the necessary file?

**Comment by lauraset** [comment]
@liuqiqi546 , please see [onedrive](https://1drv.ms/f/s!AsLBo0q3zUjCgYRfYHgM8oSZqFsiFg?e=YfJTuf).

**Comment by liuqiqi546** [comment]
> @liuqiqi546 , please see [onedrive](https://1drv.ms/f/s!AsLBo0q3zUjCgYRfYHgM8oSZqFsiFg?e=YfJTuf).

found it, thank you for the reminder.
