### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Github-Thomas-Peng** [lauraset/Super-resolution-building-height-estimation#3]
in the file: mymodels.py
from segmentation_models_pytorch.decoders.unet import UnetDecoder, UnetDecoder_noise
But there is an error:
 ImportError: cannot import name 'UnetDecoder' from 'segmentation_models_pytorch.decoders.unet',
And no module named UnetDecoder_noise. Please tell me How to solve it, thx.

**Comment by gsenxu** [comment]
Did you solve the problem?

**Comment by gsenxu** [comment]
from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder, UnetDecoder_noise
ImportError: cannot import name 'UnetDecoder_noise' from 'segmentation_models_pytorch.decoders.unet.decoder'.
How to solve this problem, thanks.

**Comment by Dengzhiyong999** [comment]
I met the same problem.

**Comment by Github-Thomas-Peng** [comment]
> from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder, UnetDecoder_noise ImportError: cannot import name 'UnetDecoder_noise' from 'segmentation_models_pytorch.decoders.unet.decoder'. How to solve this problem, thanks.

try this:
#from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder, UnetDecoder_noise
from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder

**Comment by lauraset** [comment]
> > from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder, UnetDecoder_noise ImportError: cannot import name 'UnetDecoder_noise' from 'segmentation_models_pytorch.decoders.unet.decoder'. How to solve this problem, thanks.
> 
> try this: #from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder, UnetDecoder_noise from segmentation_models_pytorch.decoders.unet.decoder import UnetDecoder

Thanks, Peng. That's correct. @gsenxu @Github-Thomas-Peng . There are some useless codes.
